version: '3.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Good practice, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
build_script:
  - cmd: dotnet build --verbosity m
  - cmd: dotnet test --no-restore --no-build
  - cmd: dotnet pack --no-restore --no-build
deploy:
 provider: NuGet
 api_key:
   secure: Zk9U7SmnxXAM8MaEg6ayyol0E1On4uSf1Gau9mekHKicSVe4Z8U15mJR7pdCKawX
 skip_symbols: true
 artifact: /.*\.nupkg/
artifacts:
 - path: '**\*.nupkg'
clone_depth: 1
on_finish:
  # Any cleanup goes here
