version: '2.1.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Good practice, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore --verbosity m
build_script:
  - cmd: dotnet pack
deploy:
  provider: NuGet
  api_key:
    secure: R29zviG5Yqpfr9G8lQEUXk9E3PLUpKJAVFNJ2YeYPhmT23+31A4fEPJ8NRJNrsKO
  skip_symbols: true
  artifact: /.*\.nupkg/
artifacts:
  - path: '**\*.nupkg'
clone_depth: 1
test_script:
  # Run all tests
  - cmd: dotnet test
on_finish:
  # Any cleanup goes here